server:
  servlet:
    context-path: "/"
    application-display-name: "bot posaderos"
  port: 8080

discord:
  token: 'ODg3MzU5NzU2MDgyMjI5Mzg5.YUDALA.XBn7_3OvceLASpP5WEsE9UuE4TY'


spreadsheet:
  id: "1lfLu5X3FU1FD2JyYBz_NllNl9UcV8dkmxmM68bTiJzY"
